# -*- coding: utf-8 -*-
"""bgr2gray_convert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUBOaHfglMU_JQVmEGtGGy71ZnEyKD9J
"""

#import libraries
import numpy as np
import cv2
import matplotlib.pyplot as plt

#upload image
img = cv2.imread('/content/baloon.jfif')

#get image channels separetly
b , g , r = img[:,:,0] , img[:,:,1] , img[:,:,2]

#convert image colour bgr to gray scale
img1 = np.uint8(np.round((b * 0.114 + g * 0.587 + r * 0.299)))

img2 = np.uint8(np.round((b * 0.0722  + g * 0.7152 + r * 0.2126)))

#display
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
fig = plt.figure(figsize=(10, 7))
fig.add_subplot(1, 3, 1)
plt.imshow(img)
plt.title("Original Image")

fig.add_subplot(1, 3, 2)
plt.imshow(img1, cmap='gray')
plt.title("Gray Image-1")

fig.add_subplot(1, 3, 3)
plt.imshow(img2, cmap='gray')
plt.title("Gray Image-2")

#plt.savefig('/content/gray_scale.png', bbox_inches='tight')